### ISSUE TITLE
ConnectionResetError: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by mukeshkham** [sassoftware/pyviyatools#107]
Hello
I received an error with callrestapi.py .
Traceback (most recent call last):
  File "callrestapi.py", line 82, in <module>
    result = callrestapi(reqval, reqtype, reqaccept, reqcontent, profile=profile)
  File "/opt/SASCLI/pyviyajob/modules/sharedmodules.py", line 111, in callrestapi
    result = requests.get(baseurl + reqval, headers=head, data=json_data)
  File "/home/test/pydev/py38-venv/lib64/python3.8/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/test/pydev/py38-venv/lib64/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/test/pydev/py38-venv/lib64/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/test/pydev/py38-venv/lib64/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/test/pydev/py38-venv/lib64/python3.8/site-packages/requests/adapters.py", line 559, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='xxxxx.xxxx.xxxxxxx', port=443): Max retries exceeded with url: /jobDefinitions/definitions (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(104, 'Connection reset by peer')))

Can you please help.

Below is the output of requests.help.

python3 -m requests.help
{
  "chardet": {
    "version": null
  },
  "charset_normalizer": {
    "version": "2.1.0"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "3.3"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.8.13"
  },
  "platform": {
    "release": "3.10.0-1160.66.1.el7.x86_64",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.28.1"
  },
  "system_ssl": {
    "version": "100020bf"
  },
  "urllib3": {
    "version": "1.26.10"
  },
  "using_charset_normalizer": true,
  "using_pyopenssl": false
}

Thanks,
Mukesh

**Comment by gerrynelson63** [comment]
What callrestapi call you are using is it a get of /jobDefinitions/definitions?

Also could you run the /showsetup.py and send the output. Thanks.

**Comment by dwstern** [comment]
Closing after two months of no activity. @mukeshkham , please feel free to reopen this issue or open another one if you still have this problem.
