### ISSUE TITLE
Report names with special characters fails using LISTREPORTS.PY

### ISSUE THREAD

**Issue by molestor** [sassoftware/pyviyatools#114]
Hi I am trying to make a complete list of reports using listreports.py
But some report names contain special danish characters æøåÆØÅ and the script fails.
I had a similar problem in issue [109]((https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsassoftware%2Fpyviyatools%2Fissues%2F109&data=05%7C01%7Cmol%40topdanmark.dk%7C2015c0fc64dc4513419108da94ca45ee%7Cd8986036513544acb219a64ab43409d5%7C0%7C0%7C637985893723893619%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=STA9n3yUVN1VeXCFIu%2FKKdUhyiD0hub6xzMTH2tjpMQ%3D&reserved=0))
which was solved by https://github.com/gerrynelson63
Maybe the same solution could be applied here.

[mola@viyt01b1 pyviyatools]$ ./listreports.py
id ,fullreport ,type ,description ,creationTimeStamp ,modifiedTimeStamp
"43392b8c-e4cf-41e1-93c0-a15865ff7021",Traceback (most recent call last):
  File "./listreports.py", line 103, in <module>
    printresult(resultdata,output_style,colsforcsv=["id","fullreport","type","description","creationTimeStamp","modifiedTimeStamp"])
  File "/opt/sas/util/pyviyatools/sharedfunctions.py", line 521, in printresult
    csvresults(result,columns=colsforcsv)
  File "/opt/sas/util/pyviyatools/sharedfunctions.py", line 447, in csvresults
    if key !=  'links' and key in columns: print('"'+str(val)+'"'+sep, end="")
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf8' in position 9: ordinal not in range(128)
[mola@viyt01b1 pyviyatools]$

**Comment by gerrynelson63** [comment]
I merged some changes last week to try to take care of this error in #113. Maybe not the best fix but it stops the error from occurring.

While researching the issue I discovered that if you run the tools using Python 3 there is no problem. If you have Python 3 that might be your best option as it has no issue printing the Danish characters. For example, you can call lisreports.py like this:

python3 listreports.py -f /gelcorp/shared/Reports
