### ISSUE TITLE
getactivityrecords.py only json output 

### ISSUE THREAD

**Issue by viya4-deployments-psd** [sassoftware/pyviyatools#187]

**Comment by viya4-deployments-psd** [comment]
I get an output only when I use 
`python3 getactivityrecords.py -o json`
using 
`python3 getactivityrecords.py -o csv`
i get 
```
Traceback (most recent call last):
  File "getactivityrecords.py", line 89, in <module>
    printresult(files_result_json, output_style, cols)
  File "/home/ubuntu/pyviyatools/sharedfunctions.py", line 624, in printresult
    csvresults(result,columns=colsforcsv,header=header)
  File "/home/ubuntu/pyviyatools/sharedfunctions.py", line 485, in csvresults
    total_items=resultdata['count']
KeyError: 'count'
```

**Comment by gerrynelson63** [comment]
@afarzam1 would you mind taking a look at this one. I could not reproduce during a quick test.

**Comment by afarzam1** [comment]
@tomstarr pointed out that this happens when the number of records exceeds the "limit", which defaults to 1000. It works if you increase the value with the --limit argument. I will increase the default limit and put in some error handling.
